### ISSUE TITLE
Support BYO certificates for all Dispatch Solo endpoints

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#669] opened 2018-10-11 20:34 UTC
### Detailed Description

Customer may configure Dispatch Solo with their own certificates.

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by kars7e** [comment] 2018-11-09 19:07
Closing as a duplicate of #642

**Closed by kars7e** 2018-11-09 19:07 UTC
Labels: Solo
