### ISSUE TITLE
Custom domains and TLS certs

### ISSUE THREAD

**Issue by imikushin** [vmware/dispatch#141] opened 2018-01-24 22:00 UTC
Dispatch users need an easy way to expose their APIs via HTTPS. 

- [ ] Bug
- [x] Feature
- [ ] Enhancement

## Detailed Description
Dispatch needs a way to:
- manage custom domains used by the apps' API endpoints
- automatically obtain and renew TLS certs needed to secure access to these API endpoints.

The user should be able to specify the domains used to access a particular API and if the access should use plain HTTP (it should, by default, support HTTPS). We assume that the user already configured DNS to route traffic targeting these domains to the Dispatch API Gateway. We also assume the use of [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication), so a single API endpoint can, in theory, be accessed via DNS-names. 

We might want to consider adding a separate entity (e.g. "Host"). APIs would be associated with Hosts (many APIs - 1 Host or many-to-many). A Host would have a hostname (domain name or IP address) and would be the object responsible for holding a TLS cert. While creating the Host, the user would be able to specify `--insecure` meaning the cert would be self-signed. At Dispatch installation time, the admin specifies the ACME server to use (by default, Let's Encrypt).

## Context
Exposing API endpoints created with `dispatch create api` through unencrypted HTTP is easy, but insecure and is becoming less and less useful. 

Using [Let's Encrypt](https://letsencrypt.org/) is a great way to automate TLS cert lifecycle.

## Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [x] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functinality
- [x] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

**Comment by seanhuxy** [comment] 2018-01-24 22:39
Note HTTP and HTTPS are already supported. I do agree this is a high priority feature of api-gateway. It's great if we could get it asap.

**Comment by berndtj** [comment] 2018-01-29 18:05
I'd like to get this feature in soon. I've got something mostly working within AWS, but it only works in that context.  Let's encrypt should work also, and may be the preferred "just works" method.

**Comment by berndtj** [comment] 2018-05-11 22:29
Duplicate of #422

**Closed by berndtj** 2018-05-11 22:29 UTC
Labels: API Gateway
